### ISSUE TITLE
Chromium messes with default output device

### ISSUE THREAD

**Issue by ad-on-is** [wwmm/easyeffects#1492]
### EasyEffects Version

6.2.4

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

I have an external BT speaker which is set as my default output device.
Let's say I have spotify running, and music plays through the BT-speaker, I open up easyeffects and the music still plays through the BT speaker, which is the expected behaviour.

However, once I open something like Discord/Slack and go to audio-settings, this is what happens.

- Pavucontrol: BT-speaker disappears for a split second, but reappears again (and remains the selected device)
- Easyeffects -> Pipewire: Switches Default output device to my laptop internal speakers

### Expected Behavior

Easyeffects should keep the default audio device.

### Debug Log

<details><summary>Log when OPENING Discord audio-settings</summary><br/>

```
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.050: pipe_manager: Stream/Input/Audio 196 Chromium input with timestamp 1650708589050327990 was added
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.052: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.052: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.053: pipe_manager: new metadata property: 196, target.node, Spa:Id, 67
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.053: pipe_manager: new metadata property: 196, target.object, Spa:Id, 23241
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.053: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.053: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.053: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.053: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.057: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.057: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.073: pipe_manager: Audio/Sink bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink was removed
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.082: node holder: 181, bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink finalized
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.090: pipe_manager: easyeffects_source port 225 is connected to Chromium input port 215
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.090: pipe_manager: easyeffects_source port 295 is connected to Chromium input port 193
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.093: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.093: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.093: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.093: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.094: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.094: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:09:49.650: pipe_manager: Audio/Sink 174 bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink with timestamp 1650708589650264977 was added
```
</details>

<details><summary>Log when CLOSING  Discord audio-settings</summary><br/>

```
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.700: pipe_manager: Stream/Input/Audio Chromium input was removed
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: cannot lookup application icon chromium in /usr/local/share/pixmaps
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: chromium icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: Chromium input disposed
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: Chromium input finalized
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: app_info: data struct destroyed
(easyeffects:106473): easyeffects-DEBUG: 12:10:25.701: node holder: 196, Chromium input finalized
(easyeffects:106473): easyeffects-DEBUG: 12:10:27.712: pipe_manager: Audio/Sink bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink was removed
(easyeffects:106473): easyeffects-DEBUG: 12:10:27.712: node holder: 174, bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink finalized
(easyeffects:106473): easyeffects-DEBUG: 12:10:28.276: pipe_manager: Audio/Sink 247 bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink with timestamp 1650708628276036607 was added
```
</details>

**Comment by wwmm** [comment]
EasyEffects doesn't even try to set default devices. In its default configuration it just try to use whatever PipeWire is telling it to be the default. Based on your logs PipeWire is destroying/recreating your bluetooth device node when discord is initialized or closed. What is really weird in my opinion. It makes no sense. The device node should be created/destroyed only when you connect or disconnect it.

**Comment by ad-on-is** [comment]
Exactly! I find this behaviour strange too. This occurs when I open Discord or Slack, which both seem to run as chromium apps. 

BTW, when EasyEffects is not running, the same happens to the BT device, then there is no sound for a second, but when it gets reattached, PW sets it back as default.

Therefore I thought, since EasyEffects picks up the internal speakers after the BT device is destroyed, and not when it's created again, it might be a bug in EasyEffects.

**Comment by wwmm** [comment]
>since EasyEffects picks up the internal speakers after the BT device is destroyed, and not when it's created again, it might be a bug in EasyEffects.

I was hoping to see in the logs a line about this switch to the internal speakers. It is strange that there is none. The next time you test try to save the full log. I would like to see which device PipeWire is reporting as default when EasyEffects initializes.

Bluetooth devices are always a pain... They are exposed like any other device. But under the hoods the audio server (PipeWire) deals with them in a very different way.

**Comment by ad-on-is** [comment]
I just grabbed the full log if it helps

https://pastebin.com/9PBccqyK

**Comment by ad-on-is** [comment]
[pw-after.txt](https://github.com/wwmm/easyeffects/files/8564723/pw-after.txt)
[pw-before.txt](https://github.com/wwmm/easyeffects/files/8564724/pw-before.txt)

**Comment by wwmm** [comment]
I almost forgot about this. THe output before has
```
id 170, type PipeWire:Interface:Node/3
 		object.serial = "23988"
 		factory.id = "8"
 		client.id = "49"
 		device.id = "144"
 		priority.session = "1010"
 		priority.driver = "1010"
 		node.description = "JBL Flip 6"
 		node.name = "bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink"
 		media.class = "Audio/Sink"
```
And the output after
```
id 120, type PipeWire:Interface:Node/3
 		object.serial = "24873"
 		factory.id = "8"
 		client.id = "49"
 		device.id = "144"
 		priority.session = "1010"
 		priority.driver = "1010"
 		node.description = "JBL Flip 6"
 		node.name = "bluez_output.F8_5C_7D_90_B6_3B.a2dp-sink"
 		media.class = "Audio/Sink"
```
The id changes. What is probably the reason for the problem and it is something I am aware I will have to improve at some point. In the past the id were unique for each device but nowadays `object.serial` will take this task. What is odd is that both the `id` and `object.serial` are changing. So even if I change the code to take decisions based on the `object.serial` value the problem may still be there. I wonder if the serial number is supposed to be changed. As far as I remember it should have the same value while the device is alive.

**Comment by sephid86** [comment]
@ad-on-is 
It could be a problem with 'pipewire-media-session'.

I too have had a similar experience.

In my case, installing 'wireplumber' solved it.

archiwiki recommends 'wireplumber' as media-session-manager.

**Comment by ad-on-is** [comment]
@sephid86 I already have wireplumber installed

**Comment by sephid86** [comment]
@ad-on-is 

sorry. I misunderstood your post.

I took a closer look at your post again and found that it was a completely different case from mine.

I hope the issue you are experiencing is resolved.

**Comment by wwmm** [comment]
@ad-on-is could you test the master branch through the AUR package? I have fixed one of the bugs related to device connection/disconnection and I am curious if it has an effect in this one too. The device disappearance can not be fixed on our side. I am almost sure this is a PipeWire bug. But at least about the reconnection of the bluetooth device we should be able to do something.

**Comment by ad-on-is** [comment]
@wwmm 
Unfortunately the issue still persists.

Just to verify:
```
Name            : easyeffects-git
Version         : 6.2.5.r87.g767654da-1
```

**Comment by wwmm** [comment]
@ad-on-is the latest update in the master branch may have some impact in this bug. When possible try to do some tests.

**Comment by ad-on-is** [comment]
@wwmm I just did, and the issue is still present. Do you want me to make a screen-recording where I replicate the issue?

**Comment by wwmm** [comment]
>Now everything works as expected ... sunglasses+1 Thank you so much! Great job!!!

Really? Finally :smile:. In this case we can close this issue. But I suggest you report to the PipeWire developers that weird bluetooth device reloading when chromium starts. It does not seem normal and it also does not seem something that is caused by EasyEffects.

**Comment by ad-on-is** [comment]
> > Now everything works as expected ... sunglasses+1 Thank you so much! Great job!!!
> 
> Really? Finally smile. In this case we can close this issue. But I suggest you report to the PipeWire developers that weird bluetooth device reloading when chromium starts. It does not seem normal and it also does not seem something that is caused by EasyEffects.

yess.. finally! 
I know that it is not caused by EasyEffects, and I experience a 1-second silence when opening chromium (even when EA is not running). Still, the other apps manage to pick up the sink where it was left of, so that's why I reported here.

Nevertheless, I 'll file an issue over at the folks of PW.
