### ISSUE TITLE
After a day or so, the headset will stop working, until I select another audio source and back

### ISSUE THREAD

**Issue by EmmanuelMess** [wwmm/easyeffects#3802]
### EasyEffects Version

~~0.3.69~~ 7.1.3

### What package are you using?

Flatpak (Flathub)

### Distribution

22.04

### Describe the bug

After a day or so of using the computer, the headphone audio will stop working (at least with Firefox), it happens for both Bluetooth and wired headphones. To make it run again I have to go to setting and select either "EasyEffects Source" if I am using a Bluetooth device or one of the "HD Audio Contollers" if its wired headphones. After the workaround it will work until there is no audio to play (YouTube video paused most likely), at which point it breaks again.

### Expected Behavior

EasyEffects works

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by EmmanuelMess** [comment]
I'm realizing that for some reason the version I have of easyeffects is very old. Isn't flatpack up to date?

**Comment by vchernin** [comment]
The version you listed is probably the pipewire version on Ubuntu 22.04. Please try check again to find the Easyeffects version.

**Comment by wwmm** [comment]
> > The version you listed is probably the pipewire version on Ubuntu 22.04. Please try check again to find the Easyeffects version.
> 
> Fixed.

I'm assuming that the issue has been fixed by the proper package upgrade. If that is not the case feel free to reopen this issue. In any case it is the kind of issue that seems to be more on PipeWire's side than on ours.

**Comment by EmmanuelMess** [comment]
> I'm assuming that the issue has been fixed by the proper package upgrade. If that is not the case feel free to reopen this issue. In any case it is the kind of issue that seems to be more on PipeWire's side than on ours.

No, I just meant to say that the stated version is the correct one now. The issue persists.

**Comment by wwmm** [comment]
> > I'm assuming that the issue has been fixed by the proper package upgrade. If that is not the case feel free to reopen this issue. In any case it is the kind of issue that seems to be more on PipeWire's side than on ours.
> 
> No, I just meant to say that the stated version is the correct one now. The issue persists.

I see. But like I said before it does not really feel like an issue inside EasyEffects. Did the computer hibernate or suspend? For reasons that could never be found sometimes this is a problem.

**Comment by EmmanuelMess** [comment]
> Did the computer hibernate or suspend? For reasons that could never be found sometimes this is a problem.

No.

**Comment by wwmm** [comment]
> > Did the computer hibernate or suspend? For reasons that could never be found sometimes this is a problem.
> 
> No.

Ok. The next time this happens run in a terminal the command `pw-dot`. Its output file can be viewed with the command `xdot` and will show how the links between filters and devices are. I think this is the first thing to clarify. Maybe the links are broken for some reason.

**Comment by EmmanuelMess** [comment]
Hmm, pw-dot seems to be always empty:
```
digraph pipewire {
}
```

**Comment by wwmm** [comment]
> Hmm, pw-dot seems to be always empty:
> 
> ```
> digraph pipewire {
> }
> ```

That is very unusual. If I remember well even if nothing is playing there should be some things there. Like your soundcard node for example.

**Comment by EmmanuelMess** [comment]
This was fixed updating pipewire.
