### ISSUE TITLE
[Bug] Blank items for audio device choosing in Pipewire tab, not remembering selected device.

### ISSUE THREAD

**Issue by craftfever** [wwmm/easyeffects#4171]
### EasyEffects Version

8.0.0

### What package are you using?

AUR (easyeffects-git)

### Distribution

Arch Linux

### Describe the bug

<img width="1113" height="729" alt="Image" src="https://github.com/user-attachments/assets/fe96612e-203d-481a-ab6c-e26e5c0d45a7" />

The thing is, EasyEffects does not remember audio device/sink, which I choosing from drop-down menu and, when I check "Use default output (input)", audio can become muted (technically chain breaks) 'cause EE doesn't remember audio devices/sinks in system. So it is not problem just in interface (QML) (maybe...)

### Expected Behavior

Successfully remembering chose device and correct behavior, when checking "Use default input/output" option.

**Comment by wwmm** [comment]
Hum... I think I fixed this bug last night. Did you try to recompile the package?

**Comment by wwmm** [comment]
I am doing some tests and it is fine on my side. But yesterday I could reproduce it. So the fix should still be working.

**Comment by craftfever** [comment]
> I am doing some tests and it is fine on my side. But yesterday I could reproduce it. So the fix should still be working.

Sorry, I can still reproduce it. It especially happens, when I switching from Output/input tab to Pipewire tab, items is blank. New recent recompile.

**Comment by wwmm** [comment]
Hum... Try to get logs so we can see if anything unusual happens. Yesterday I tested this several times but I could not reproduce it. Even plugging and unplugging the output device while "use default" was disabled worked fine.

**Comment by craftfever** [comment]
> Hum... Try to get logs so we can see if anything unusual happens. Yesterday I tested this several times but I could not reproduce it. Even plugging and unplugging the output device while "use default" was disabled worked fine.

Strangely, items appears after a delay (approx 4-5 sec.) and it seems that default input/output switch not buggy anymore, but I'm continue testing.

**Comment by wwmm** [comment]
This finally happened here on my computer. I think I know what might be going on.

**Comment by wwmm** [comment]
Master branch updated. As far as I can see it seems fixed now.

**Comment by craftfever** [comment]
> This finally happened here on my computer. I think I know what might be going on.

I noticed that item appears, when I open Plasma sound panel, for example< or other audio mixer, then items appears in case with bug. After your fix with sinks update handling, everything work now, thanks again.
