### ISSUE TITLE
Autostart option adds a `gnome-.desktop` file in the autostart config folder

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#4298]
As the title says.

<p><img width="493" height="86" alt="Image" src="https://github.com/user-attachments/assets/f33d463d-1b84-46b3-8ce8-389bf57f1f61" /></p>

Content of the file:

```
[Desktop Entry]
Type=Application
Name=gnome-
X-XDP-Autostart=gnome-
Exec=easyeffects --service-mode --hide-window
```

Is this normal? Shouldn't it be `easyeffects.desktop`?

**Comment by wwmm** [comment]
> Is this normal? Shouldn't it be `easyeffects.desktop`?

Hum... Right now the whole thing is managed by libportal. At least on my computer if I enable autostart using the EE installed in the system I get
```
wallace@wwmm ~ $ cat .config/autostart/com.github.wwmm.easyeffects.desktop 
[Desktop Entry]
Type=Application
Name=com.github.wwmm.easyeffects
X-XDP-Autostart=com.github.wwmm.easyeffects
Exec=easyeffects --service-mode --hide-window
```

Did you try with an EE instance running in a local folder or with the EE exe installed in the system folders?

**Comment by Digitalone1** [comment]
The AUR package. The executable is placed in `/usr/bin/easyeffects`.

That's clearly something wrong with the portal. But, to my huge surprise, even after deleting that file, Easy Effects is still starting at the system startup. 😲

Is Gnome implementing something to restore the applications that were previously running at the shutdown? 🤔

Update: Even after i terminate the service prior the shutdown. At the restart the app is auto started without the desktop file in `~/.conf/autostart`. Who the hell is starting it?

**Comment by wwmm** [comment]
> Update: Even after i terminate the service prior the shutdown. At the restart the app is auto started without the desktop file in `~/.conf/autostart`. Who the hell is starting it?

In this case GNOME must be restoring the last used session. You can test that by keeping more apps open before a logout. If they also come back GNOME is the one restarting them.

As far as I remember this is usually disabled by default. KDE can do the same thing.

**Comment by wwmm** [comment]
>The AUR package. The executable is placed in /usr/bin/easyeffects.

That is odd. I use it too and libportal created that file I showed above... My intention when using only libportal was simplifying the autostart management. But if it starts to behave in weird ways we may have to add that manual management back.

**Comment by Digitalone1** [comment]
> In this case GNOME must be restoring the last used session. You can test that by keeping more apps open before a logout. If they also come back GNOME is the one restarting them.
> 
> As far as I remember this is usually disabled by default. KDE can do the same thing.

Okay, but there's also something wrong in EE because I disabled the service mode and closed the app. EE was not running and I supposed the service option was disabled. Unfortunately, when I restart the system, Easy Effects is autostarted and when I check the service mode option in the preferences, **it's enabled**. Why? Is something we do in particular to manage this option?

> That is odd. I use it too and libportal created that file I showed above... My intention when using only libportal was simplifying the autostart management. But if it starts to behave in weird ways we may have to add that manual management back.

Yes. And I think this should be a stopper for the next release unfortunately.

**Comment by wwmm** [comment]
>Unfortunately, when I restart the system, Easy Effects is autostarted and when I check the service mode option in the preferences, it's enabled

It feels like the database was not able to save the value. What is strange considering that ass soon as the window is closed it tries to do that.

>Yes. And I think this should be a stopper for the next release unfortunately.

Let me see what happens if I try to recreate the autostar file. Maybe there was a big regression in libportal.

**Comment by wwmm** [comment]
> Maybe there was a big regression in libportal.

Does not seem to be the case. After I disabled the autostart in EE preferences window the autostart file was as expected removed. And after enabling the autostart again libportal created the `com.github.wwmm.easyeffects.desktop` with the correct content I pasted in the previous comment. It seems something odd is happening when running inside GNOME.

**Comment by Digitalone1** [comment]
This is what I did:

1. Open EE and select the preferences tab.
2. The service mode is enabled and the autostart is disabled.
3. Disable the service mode.
4. Close the window.
5. EE app is not running in background.
6. Reopen the app and select the preferences tab.
7. The service mode is correctly disabled and the autostart is disabled as before.
8. Close the window.
9. EE app is not running in background.
10. Restart the system.
11. At the new login I see EE app running in the background (something has autostarted it).
12. Open EE window and select the preferences tab.
13. The autostart is disabled, but **the service mode is enabled**.

This is unbelievable.

**Comment by vchernin** [comment]
Some general portal things to sanity check:

Make sure `xdg-desktop-portal`, `xdg-desktop-portal-gnome` (if on gnome) and `xdg-desktop-portal-gtk` services are running.

Also make sure the configuration file is set correctly. There should be one shipped with your desktop environment, I believe it is somewhere in `/usr/share/xdg-desktop-portal`. https://flatpak.github.io/xdg-desktop-portal/docs/configuration-file.html

**Comment by wwmm** [comment]
> This is what I did:
> 
>     1. Open EE and select the preferences tab.
> 
>     2. The service mode is enabled and the autostart is disabled.
> 
>     3. Disable the service mode.
> 
>     4. Close the window.
> 
>     5. EE app is not running in background.
> 
>     6. Reopen the app and select the preferences tab.
> 
>     7. The service mode is correctly disabled and the autostart is disabled as before.
> 
>     8. Close the window.
> 
>     9. EE app is not running in background.
> 
>     10. Restart the system.
> 
>     11. At the new login I see EE app running in the background (something has autostarted it).
> 
>     12. Open EE window and select the preferences tab.
> 
>     13. The autostart is disabled, but **the service mode is enabled**.
> 
> 
> This is unbelievable.

I tried the same steps. Including the system restart. There was no EE process running when KDE session started. Yeah... GNOME or something else is forcing an EE start on your system. And maybe the same thing is messing with the information libportal is using to create the desktop file.

**Comment by wwmm** [comment]
And the system tray icon setting? Is it enabled or disabled @Digitalone1 ? I followed your steps with it disabled as GNOME does not show the tray icon. But I usually have it enabled on KDE. Not that the tray icon should be making any difference on this.

**Comment by Digitalone1** [comment]
> And the system tray icon setting? Is it enabled or disabled [@Digitalone1](https://github.com/Digitalone1) ?

It's disabled and grayed out. Anyway, Gnome does not implement the session restore since the Wayland protocol is not supported.

**Comment by wwmm** [comment]
> It's disabled and grayed out. Anyway, Gnome does not implement the session restore since the Wayland protocol is not supported.

Hum... Strange I think I enabled that once through gnome tweaks but I may be confusing things. In any case what is the content of the file `.config/easyeffects/db/easyeffectsrc` after you disable the service setting and closes EE window or finishes its process?

**Comment by Digitalone1** [comment]
> Make sure `xdg-desktop-portal`, `xdg-desktop-portal-gnome` (if on gnome) and `xdg-desktop-portal-gtk` services are running.

```
$ systemctl --user status xdg-desktop-portal.service
● xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Fri 2025-11-07 18:58:47 CET; 15min ago
 Invocation: 8d4ba716366549e0a4e8926cb41cdbfb
   Main PID: 2918 (xdg-desktop-por)
      Tasks: 7 (limit: 18236)
     Memory: 4.6M (peak: 6.1M)
        CPU: 105ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal.service
             └─2918 /usr/lib/xdg-desktop-portal

$ systemctl --user status xdg-desktop-portal-gnome.service
● xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gnome.service; static)
     Active: active (running) since Fri 2025-11-07 18:58:47 CET; 15min ago
 Invocation: d4c1ff4d4a624be7a97dab9272a29ce8
   Main PID: 2948 (xdg-desktop-por)
      Tasks: 6 (limit: 18236)
     Memory: 14M (peak: 15.1M)
        CPU: 235ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gnome.servi>
             └─2948 /usr/lib/xdg-desktop-portal-gnome

$ systemctl --user status xdg-desktop-portal-gtk.service
● xdg-desktop-portal-gtk.service - Portal service (GTK/GNOME implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-gtk.service; static)
     Active: active (running) since Fri 2025-11-07 18:58:47 CET; 15min ago
 Invocation: d7b340fa165d468cad7190b7ca126ca6
   Main PID: 4031 (xdg-desktop-por)
      Tasks: 6 (limit: 18236)
     Memory: 9M (peak: 9.8M)
        CPU: 87ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-gtk.service
             └─4031 /usr/lib/xdg-desktop-portal-gtk

```

> Also make sure the configuration file is set correctly. There should be one shipped with your desktop environment, I believe it is somewhere in `/usr/share/xdg-desktop-portal`. https://flatpak.github.io/xdg-desktop-portal/docs/configuration-file.html

I have them. The line `org.freedesktop.impl.portal.Access=gnome-shell;gtk;` is missing in `gnome-portals.conf`, but this file is set by Gnome in the [gnome-session](https://archlinux.org/packages/extra/x86_64/gnome-session/) package, so I suppose the defaults are correct....

**Comment by Digitalone1** [comment]
> Hum... Strange I think I enabled that once through gnome tweaks but I may be confusing things. In any case what is the content of the file `.config/easyeffects/db/easyeffectsrc` after you disable the service setting and closes EE window or finishes its process?

```
[EffectsPipelines]
ignoreSystemNotifications=true
inactivityTimeout=15
useCubicVolumes=true

[Spectrum]
dynamicYScale=false
height=130
nPoints=200
spectrumColorScheme=automatic
spectrumColorTheme=blueSeries
spectrumShape=dots
state=false

[StreamInputs]
inputDevice=alsa_input.pci-0000_04_00.6.HiFi__Mic1__source

[StreamOutputs]
mostUsedPresets=LoudnessCrystalEqualizer,AutoGainSpeaker,LoudnessCrystalEqualizer with Maximizer,AutoGainSpeaker2,LoudnessEqualizer
outputDevice=alsa_output.pci-0000_04_00.6.HiFi__Speaker__sink
plugins=gate#0,compressor#0,multiband_compressor#0,crystalizer#0,equalizer#0,limiter#0
showBlocklistedApps=true
usedPresets=LoudnessCrystalEqualizer:822,LoudnessCrystalEqualizerHP:5,OnlyLM:5,LoudnessEqualizer:15,ReferenceHeadphones:2,LoudnessEqualizerHeadphones:1,AutoGainSpeaker:113,OnlyLimiter:5,LoudnessCrystalEqualizer with Maximizer:42,OnlyMaximizer:6,TestConvolver:1,AutoGainSpeaker2:39,TestRNNoise:1,Koss 48k Filtered Notch:8
visiblePage=pluginsPage
visiblePlugin=gate#0

[Window]
enableServiceMode=false
height=618
lastLoadedOutputPreset=LoudnessCrystalEqualizer
outputAutoloadingFallbackPreset=LoudnessCrystalEqualizer
outputAutoloadingUsesFallback=true
showNativePluginUi=true
width=1256
xdgGlobalShortcuts=true
xdgGlobalShortcutsBound=true
```

**Comment by wwmm** [comment]
>[Window]
>enableServiceMode=false

And you do not have `autostartOnLogin=true` set as I have. So a database failure when saving your changes is not what is happening. It really feels like an external agent is starting EE.

**Comment by Digitalone1** [comment]
Okay, now I checked for hidden files in autostart and that's what I found:

<p><img width="448" height="76" alt="Image" src="https://github.com/user-attachments/assets/c7552c5c-12f3-4819-82a1-d595b2e3854b" /></p>

```
[Desktop Entry]
Type=Application
Name=
X-XDP-Autostart=
Exec=easyeffects --service-mode --hide-window
```

So I had two different files that were starting EE at the startup...

Now I'd like to understand if this is an issue of my system or just the whole Gnome. Because if it's the second, I don't think we can push the new release causing these problems to other Gnome users.

**Comment by wwmm** [comment]
> Now I'd like to understand if this is an issue of my system or just the whole Gnome. Because if it's the second, I don't think we can push the new release causing these problems to other Gnome users.

I doubt it is a GNOME problem. Most likely at some point you used the autostart switch when running an instance from a local folder instead of the one installed in your system. In a case like this libportal takes the name of the parent process. usually the terminal. But maybe in your case you used something to launch the process that caused libportal to use an empty string.

For our end users this isn't a concern because in general they will launch EE through the dektop menu.

**Comment by wwmm** [comment]
Unless launching an app through gnome app launcher is causing this behavior. In this case we will have to bring the manual handling back.

**Comment by Digitalone1** [comment]
> And you do not have `autostartOnLogin=true` set as I have. So a database failure when saving your changes is not what is happening. It really feels like an external agent is starting EE.

Okay, but if I have `enableServiceMode=false`, why is it turned to **true** when EE is autostarted? Shouldn't it stay as false even when the system autostart it? Maybe I want to autostart it without service mode...

> I doubt it is a GNOME problem. Most likely at some point you used the autostart switch when running an instance from a local folder instead of the one installed in your system. In a case like this libportal takes the name of the parent process. usually the terminal. But maybe in your case you used something to launch the process that caused libportal to use an empty string.
> 
> For our end users this isn't a concern because in general they will launch EE through the dektop menu.

I saw the wrong name even toggling the autostart option from the AUR package executable. I will test it another time and let you know...

**Comment by wwmm** [comment]
>why is it turned to true when EE is autostarted? Shouldn't it stay as false even when the system autostart it? Maybe I want to autostart it without service mode...

As the autostart in the gtk code forced service mode I implemented things the same way. But it is totally possible to build the desktop file without forcing `--service-mode`. It could be added only if the user already has service mode enabled in its preferences.

**Comment by wwmm** [comment]
> But it is totally possible to build the desktop file without forcing `--service-mode`. It could be added only if the user already has service mode enabled in its preferences.

I've updated our master branch with this.

**Comment by Digitalone1** [comment]
So, now I'm toggling the autostart option and this is the filename: `com.github.wwmm.easyeffects.desktop`

And this is the content: 

```
[Desktop Entry]
Type=Application
Name=com.github.wwmm.easyeffects
X-XDP-Autostart=com.github.wwmm.easyeffects
Exec=easyeffects --service-mode --hide-window
```

So all of this because I generated the file in the dev mode which gave a different name which, in turn, was assigning the wrong name even in the AUR executable. 😧

I will test it further. Maybe the issues I was having with the global shortcuts were caused by this...

**Comment by wwmm** [comment]
>So all of this because I generated the file in the dev mode which gave a different name which, in turn, was assigning the wrong name even in the AUR executable. 😧

I saw something similar in the past. But it was a little less weird. It was a proper name. But the name of yakuake's terminal instead of EE name. Libportal really wants to match process and desktop file from the system installation.

**Comment by wwmm** [comment]
I've updated our master branch again adding a fallback member function to the autostart class just in case we need to do this the old way. For now the function is not used but we could if necessary call it based on the the value of `XDG_SESSION_DESKTOP` and `XDG_CURRENT_DESKTOP` if there is a desktop that actually needs a workaround.

This is one of the reasons why I think it is time for a release. Some small details will only reveal themselves as more people use the program. And so far it does not seem we went beyond the land of gnome and kde.

**Comment by wwmm** [comment]
> but we could if necessary call it based on the the value of `XDG_SESSION_DESKTOP` and `XDG_CURRENT_DESKTOP` if there is a desktop that actually needs a workaround.

This alone is not enough because Flatpak users HAVE to use libportal no matter what. So a fallback has to consider the desktop and if EE is inside flatpak sandbox or not. Only outside of Flatpak calling the workaround is viable. @vchernin what is the way to figure out if we are inside Flatpak? Still checking if a certain file exists? I forgot the details...

**Comment by wwmm** [comment]
>Maybe the issues I was having with the global shortcuts were caused by this...

It is possible. Global shortcuts do not work right for me when using a local folder instance because KDE uses the terminal information when creating the shortcut instead of EE info.

**Comment by Digitalone1** [comment]
> It is possible. Global shortcuts do not work right for me when using a local folder instance because KDE uses the terminal information when creating the shortcut instead of EE info.

Indeed default global shortcuts are working after a reboot, so this comment https://github.com/wwmm/easyeffects/issues/3834#issuecomment-3503709312 is outdated.

**Comment by vchernin** [comment]
> This alone is not enough because Flatpak users HAVE to use libportal no matter what. So a fallback has to consider the desktop and if EE is inside flatpak sandbox or not. Only outside of Flatpak calling the workaround is viable. [@vchernin](https://github.com/vchernin) what is the way to figure out if we are inside Flatpak? Still checking if a certain file exists? I forgot the details...

Most sensible solution is to check for the existence of `/.flatpak-info`. If that file exists, the app is running a flatpak sandbox.

**Comment by Digitalone1** [comment]
> I've updated our master branch again adding a fallback member function to the autostart class just in case we need to do this the old way. For now the function is not used but we could if necessary call it based on the the value of `XDG_SESSION_DESKTOP` and `XDG_CURRENT_DESKTOP` if there is a desktop that actually needs a workaround.
> 
> This is one of the reasons why I think it is time for a release. Some small details will only reveal themselves as more people use the program. And so far it does not seem we went beyond the land of gnome and kde.

I suggest to use the fallback whenever we are outside the Flatpak sandbox. This way we are sure it works in all desktops not using the sandbox. I know the issue and will avoid it, but maybe other developers who want to contribute may incur into the same issue while testing the dev executable.

**Comment by wwmm** [comment]
> I suggest to use the fallback whenever we are outside the Flatpak sandbox. This way we are sure it works in all desktops not using the sandbox. I know the issue and will avoid it, but maybe other developers who want to contribute may incur into the same issue while testing the dev executable.

Ok. It should be fine to do this. In a few minutes I will update the master branch.

**Comment by Digitalone1** [comment]
Anyway, looking at https://github.com/wwmm/easyeffects/commit/a51ab94aeb04fd721c4cb25140e29c74e3f469f8 I think there's still an inconsistency.

If I previously enable the autostart and then the service mode, I might think the app will start in service mode, but it won't do that because the portal function was invoked when the service mode was disabled. 

To be more consistent, should we recall the portal function whenever the service mode is changed?

Something like

```c++
connect(db::Main::self(), &db::Main::serviceModeChanged, [&]() {
  if (!db::Main::autostartEnabled()) {
    return;
  }

  // Update --service-mode option in autostart command line
  update_background_portal();
}
```

**Comment by wwmm** [comment]
> Anyway, looking at [a51ab94](https://github.com/wwmm/easyeffects/commit/a51ab94aeb04fd721c4cb25140e29c74e3f469f8) I think there's still an inconsistency.
> 
> If I previously enable the autostart and then the service mode, I might think the app will start in service mode, but it won't do that because the portal function was invoked when the service mode was disabled.
> 
> To be more consistent, should we recall the portal function whenever the service mode is changed?
> 
> Something like
> 
> connect(db::Main::self(), &db::Main::serviceModeChanged, [&]() {
>   if (!db::Main::autostartEnabled()) {
>     return;
>   }
> 
>   // Update --service-mode option in autostart command line
>   update_background_portal();
> }

It makes sense. I will do that now.

>I suggest to use the fallback whenever we are outside the Flatpak sandbox. This way we are sure it works in all desktops not using the sandbox. I know the issue and will avoid it, but maybe other developers who want to contribute may incur into the same issue while testing the dev executable.

Done. One advantage is that the old way allows us to set `X-GNOME-Autostart-Phase` and `X-KDE-autostart-phase=2`. For some reason libportal does not allow us to set anything extra to the desktop file.

**Comment by wwmm** [comment]
> It makes sense. I will do that now.

Done. I think that within 1 or 2 hours I will make the release. The things that are left to be polished can be done in the usual flow of minor releases. Like trying to make Qt be more gentle on memory usage. It does the same kind of aggressive widget caching gtk does but it seems to be even more aggressive...

I am also not happy with using WebEngineView to load the manual html pages. The usability is very nice. But it uses too much memory. But any good solution to that involves rewriting the whole manual in a way that no javascript is used by the webpages. Or using a completely new format that is somehow nice on resources. What again requires rewriting the whole manual. What probably will consume a lot of time. So let's move on and improve this along the way...

**Comment by Digitalone1** [comment]
@wwmm There's still an issue. We should use the same string used by libportal as the filename for the autostart desktop entry. I'm testing the recent changes and this is what happened:

<p><img width="531" height="138" alt="Image" src="https://github.com/user-attachments/assets/fda1f9c4-93e3-47cc-b494-3c928f3b4d1d" /></p>

This is an edge case, but we use `com.github.wwmm.easyeffects.desktop` for the desktop entry in `usr/share/applications`, so I think we should use the same name for the autostart entry.

`com.github.wwmm.easyeffects.desktop` is already used in the code, maybe it's already a constant. You can reuse it for the filename.  

For the release, I suggest to not rush it. With all the changed we did, maybe it's better to wait a little more. You can do it tomorrow.

**Comment by vchernin** [comment]
@Digitalone1 I intentionally changed it to use a different name `APPLICATION_ID_SHORT`/`applicationIdShort` so it would not conflict with the flatpak created files. But if that approach is causing issues this can be fixed by replacing `APPLICATION_ID_SHORT` with `APPLICATION_ID`. That simplifies things anyways so I think using the verbose name is ok.

**Comment by wwmm** [comment]
> [@Digitalone1](https://github.com/Digitalone1) I intentionally changed it to use a different name `APPLICATION_ID_SHORT`/`applicationIdShort` so it would not conflict with the flatpak created files. But if that approach is causing issues this can be fixed by replacing `APPLICATION_ID_SHORT` with `APPLICATION_ID`. That simplifies things anyways so I think using the verbose name is ok.

I think that what she is talking about has to do with the renaming I unconsciously did a few hours ago. I wrote `easyeffects-service.desktop` there instead of using `com.github.wwmm.easyeffects.desktop` like libportal does. But I think the name of the file inside the autostart folder has no consequence. This would be a problem for the desktop file installed in the system folder.

**Comment by wwmm** [comment]
It probably will work both ways. But it makes sense to use `APPLICATION_ID` there so we behave like other KDE's app do when they create an autostart file. I will update the master branch.

**Comment by Digitalone1** [comment]
> I think that what she is talking about has to do with the renaming I unconsciously did a few hours ago. I wrote `easyeffects-service.desktop` there instead of using `com.github.wwmm.easyeffects.desktop` like libportal does. 

Yes, I was talking about the local user autostart config folder.

**Comment by Digitalone1** [comment]
> But I think the name of the file inside the autostart folder has no consequence.

Instead I think it matters a lot because now global shortcuts are not working again. And maybe this has to do with the fact that the system autostarted with `easyeffects-service.desktop`.

I terminated the service and restarted the app by the Gnome dash and the shortcuts returned to work.

**Comment by wwmm** [comment]
> > But I think the name of the file inside the autostart folder has no consequence.
> 
> Instead I think it matters a lot because now global shortcuts are not working again. And maybe this has to do with the fact that the system autostarted with `easyeffects-service.desktop`.
> 
> I terminated the service and restarted the app by the Gnome dash and the shortcuts returned to work.

Oh... This is probably the only exception. I still think it is really an odd design choice that they do not allow the application to set the proper name at runtime and rely on the desktop file name...

**Comment by Digitalone1** [comment]
> Oh... This is probably the only exception. I still think it is really an odd design choice that they do not allow the application to set the proper name at runtime and rely on the dekstop file name...

Yeah. I recompiled the master branch and deleted the old desktop file. Recreated the new one and restarted... now the global shortcuts work.
