### ISSUE TITLE
Some pages are misaligned

### ISSUE THREAD

**Issue by wxq1884482** [wwmm/easyeffects#4506]
### EasyEffects Version

8.0.3

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Adjusting the scaling factor to less than 1 using gnome-tweaks may cause slight misalignment of the page.

<img width="736" height="381" alt="Image" src="https://github.com/user-attachments/assets/bebe60c7-d83c-41d3-833d-f6613817b7d8" />

### Expected Behavior

Adjust the page zoom, my device is set to 0.85 scale.

### Debug Log

[admin1@archlinux ~]$ export G_MESSAGES_DEBUG=easyeffects
[admin1@archlinux ~]$ easyeffects 
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/output
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/rnnoise directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/output
easyeffects: stream_input_effects.cpp:245	Before: 74 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: stream_input_effects.cpp:245	Before: 74 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: main.cpp:154	Disabling global bypass
QWebEngineDesktopMediaRequest is neither a default constructible QObject, nor a default- and copy-constructible Q_GADGET, nor a QObject marked as uncreatable.
You should not use it as a QML type.
qrc:/qt/qml/ee/type/presets/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/type/presets/contents/ui/Main.qml:221:5: QML ShortcutsSheet: Binding loop detected for property "implicitHeight":
qrc:/qt/qml/org/kde/kirigami/templates/OverlaySheet.qml:139:5

**Comment by lIL1521** [comment]
To add another issue: opening the main interface also results in higher CPU usage than expected.

**Comment by Digitalone1** [comment]
Hello. Maybe there's a QML option to center vertically the text in the spinbox. I'll try to investigate.

**Comment by Digitalone1** [comment]
@wxq1884482  Unfortunately, I'm not able to reduce the font size. Please test `easyeffects-git` from AUR on your system when #4512 is merged.

**Comment by wwmm** [comment]
I wonder how much of this can actually be properly fixed on the application side. It may be one of those situations where the fix should be done in Qt or KDE libraries.

**Comment by Digitalone1** [comment]
> I wonder how much of this can actually be properly fixed on the application side. It may be one of those situations where the fix should be done in Qt or KDE libraries.

Actually setting the horizontal alignment to center worked, but I didn't added it to the merge request since some localization may need to align at right (by default it follows the writing system, at least that was reported in the documentation).

Setting the vertical alignment to center does not change anything to me because the text is large enough to fit the input field and I cannot lower its size even changing the font factor from Gnome Tweaks. So I can't test if the vertical alignment works. 

If you can change the font size on KDE, please test it.

**Comment by lIL1521** [comment]
However, I am using the GNOME desktop environment (GTK), which I may not be able to do accurate testing, but I will try to use a virtual machine to use the KDE desktop environment and do more precise problem research and reproduction
In the meantime, thank you for your further reply to the question

**Comment by lIL1521** [comment]
The current log updates are as follows：
[admin1@archlinux ~]$ export G_MESSAGES_DEBUG=easyeffects
[admin1@archlinux ~]$ easyeffects 
easyeffects: stream_input_effects.cpp:245	Before: 57 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/output
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/rnnoise directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/output
easyeffects: stream_input_effects.cpp:245	Before: 57 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: main.cpp:154	Disabling global bypass
QWebEngineDesktopMediaRequest is neither a default constructible QObject, nor a default- and copy-constructible Q_GADGET, nor a QObject marked as uncreatable.
You should not use it as a QML type.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/Main.qml:223:5: QML ShortcutsSheet: Binding loop detected for property "implicitHeight":
qrc:/qt/qml/org/kde/kirigami/templates/OverlaySheet.qml:139:5
qrc:/qt/qml/org/kde/desktop/ScrollBar.qml:78:13: TypeError: Cannot read property 'horizontal' of null
file:///usr/lib/qt6/qml/org/kde/kirigami/ScrollablePage.qml:274:13: TypeError: Cannot read property 'flickable' of null
qrc:/qt/qml/ee/ui/contents/ui/PipeWirePage.qml:12:1: QML PipeWirePage: Created graphical object was not placed in the graphics scene.
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PipeWirePage.qml:12:1: QML PipeWirePage: Created graphical object was not placed in the graphics scene.
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PipeWirePage.qml:12:1: QML PipeWirePage: Created graphical object was not placed in the graphics scene.
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PipeWirePage.qml:12:1: QML PipeWirePage: Created graphical object was not placed in the graphics scene.
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PipeWirePage.qml:12:1: QML PipeWirePage: Created graphical object was not placed in the graphics scene.
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:11:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/PipeWirePage.qml:12:1: QML PipeWirePage: Created graphical object was not placed in the graphics scene.
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*
file:///usr/lib/qt6/qml/org/kde/kirigami/Page.qml:199: Error: Cannot assign [undefined] to QQuickItem*ng loop detected for property "implicitHeight":
qrc:/qt/qml/org/kde/kirigami/templates/OverlaySheet.qml:139:5

However, some transition animations are missing, and certain elements cannot be fully displayed even when maximized.
The above content may already include logs related to animation display issues.

About images where elements may not display correctly:
<img width="627" height="379" alt="Image" src="https://github.com/user-attachments/assets/275bc5af-6c37-462b-8b9d-20a7b4250794" />

Also, on the audio input interface, even when no sound is being played, the processor usage remains high.

I hope the above issues can be resolved.

**Comment by Digitalone1** [comment]
At least the vertical alignment has been fixed. We should increase the spinbox width in the UI of some plugins. @wxq1884482 Can you list which effects have this issue? Thanks.

**Comment by lIL1521** [comment]
Sorry, I remembered the original effect incorrectly. I previously thought there should be a conversion effect in the sound effects section, but that was an old version of GTK.
But that CPU, when opening the input/output interface of a program, should maintain a low CPU usage if there is no program outputting audio, rather than being relatively high, in my opinion.

https://github.com/user-attachments/assets/b20f297d-0735-4dcd-ac47-0e0a556a272c

But if this is the correct rendering, I think the processor usage issue can probably be ignored.

**Comment by wwmm** [comment]
>But that CPU, when opening the input/output interface of a program, should maintain a low CPU usage if there is no program outputting audio, rather than being relatively high, in my opinion.

Sometimes pipewire is playing silent buffers. Try to run in a terminal the command `pw-top` so we can see if there is active or not in the filters. If not then it is entirely a Qt issue.

**Comment by lIL1521** [comment]
No, PipeWire does not play silent buffers, and this usage issue only occurs when a specific interface is opened.
The situation is shown in the picture below:

<img width="1867" height="1019" alt="Image" src="https://github.com/user-attachments/assets/f65128e0-6e40-45a9-abf0-fbb436b37a06" />

Looking forward to your reply.

> > But that CPU, when opening the input/output interface of a program, should maintain a low CPU usage if there is no program outputting audio, rather than being relatively high, in my opinion.
> 
> Sometimes pipewire is playing silent buffers. Try to run in a terminal the command `pw-top` so we can see if there is active or not in the filters. If not then it is entirely a Qt issue.

**Comment by wwmm** [comment]
>Looking forward to your reply.

Oh... Now I remember that in the Qt code we use everywhere an approach that in the Gtk code we used only for the spectrum. Instead of the plugin asking the interface to be updated the interface is the one periodically reading the plugins parameters. If you switch to the pipewire tab the cpu usage probably will go because this tab has no level meter or spectrum to draw. 

I have to think about a way to optimize this. The old approach has its own issues. As the filters process values in pipewire's realtime thread they can't directly update the window widgets. They had to schedule callbacks in the main thread. But that caused lots of hard to fix bugs in the gtk code because synchronizing what happens in the plugins thread with the gui thread can be quite challenging. Another problem was that the window animations for the spectrum and the level meters did not feel smooth. Some users complained about that. 

I think it should be possible to set a flag when our pipeline filters are unlinked. This way we could disable Qt's frame animation callback in this situation. They obviously have to be active when the pipeline filters are linked. I will add that to our todo list.

**Comment by wwmm** [comment]
> I think it should be possible to set a flag when our pipeline filters are unlinked. This way we could disable Qt's frame animation callback in this situation. They obviously have to be active when the pipeline filters are linked. I will add that to our todo list.

Implemented. You can test it through the AUR pacakge.

**Comment by lIL1521** [comment]
Thanks for the reply, but I’ve found a new issue,this is a problem that has appeared in the latest version of Git. When the software is completely closed, the convolution reverb settings may be lost and need to be set again.

The video demonstration is as follows：

https://github.com/user-attachments/assets/5c4c8997-c7c2-4e36-bfcb-05029e58dc21

Looking forward to your reply

> Implemented. You can test it through the AUR pacakge.

**Comment by lIL1521** [comment]
This is an interface display problem, but it has actually been set.

> Thanks for the reply, but I’ve found a new issue,this is a problem that has appeared in the latest version of Git. When the software is completely closed, the convolution reverb settings may be lost and need to be set again.
> 
> The video demonstration is as follows：
> 
> https://github.com/user-attachments/assets/5c4c8997-c7c2-4e36-bfcb-05029e58dc21
> 
> Looking forward to your reply
> 
> > Implemented. You can test it through the AUR pacakge.
> 
>

**Comment by Digitalone1** [comment]
Is this happening only to the Convolver?

**Comment by lIL1521** [comment]
I'm not sure about that. What I do know is that the Convolver function has a problem,to display it correctly, you need to select a different IRS file and then select the original IRS file again.

> Is this happening only to the Convolver?

**Comment by Digitalone1** [comment]
> I'm not sure about that. What I do know is that the Convolver function has a problem,to display it correctly, you need to select a different IRS file and then select the original IRS file again.

@wwmm Maybe is this related to the recent changes to the worker thread?

**Comment by wwmm** [comment]
> > I'm not sure about that. What I do know is that the Convolver function has a problem,to display it correctly, you need to select a different IRS file and then select the original IRS file again.
> 
> @wwmm Maybe is this related to the recent changes to the worker thread?

I will test again. But the only regression I remember having seen I fixed yesterday. The chart was updated only when audio was going through easyeffects.

**Comment by Digitalone1** [comment]
I have to say that I can't reproduce this issue. On the dev build, closing and reopening the window I still see the spectrum of the loaded Convolver IR.

**Comment by lIL1521** [comment]
> I have to say that I can't reproduce this issue. On the dev build, closing and reopening the window I still see the spectrum of the loaded Convolver IR.

This is my reproduction log:

[admin1@archlinux ~]$ export G_MESSAGES_DEBUG=easyeffects
[admin1@archlinux ~]$ easyeffects 
easyeffects: stream_input_effects.cpp:245	Before: 60 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/output
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/rnnoise directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/output
easyeffects: plugin_base.cpp:499	soe: convolver is disconnected
easyeffects: plugin_base.cpp:499	soe: deesser is disconnected
easyeffects: plugin_base.cpp:499	soe: maximizer is disconnected
easyeffects: stream_input_effects.cpp:245	Before: 60 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: main.cpp:154	Disabling global bypass
QWebEngineDesktopMediaRequest is neither a default constructible QObject, nor a default- and copy-constructible Q_GADGET, nor a QObject marked as uncreatable.
You should not use it as a QML type.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:10:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/Main.qml:223:5: QML ShortcutsSheet: Binding loop detected for property "implicitHeight":
qrc:/qt/qml/org/kde/kirigami/templates/OverlaySheet.qml:139:5
easyeffects: plugin_base.cpp:499	soe: convolver is disconnected
easyeffects: plugin_base.cpp:499	soe: deesser is disconnected
easyeffects: plugin_base.cpp:499	soe: maximizer is disconnected
easyeffects: plugin_base.cpp:499	soe: spectrum is disconnected
easyeffects: plugin_base.cpp:499	soe: output_level is disconnected
easyeffects: plugin_base.cpp:499	sie: spectrum is disconnected
easyeffects: plugin_base.cpp:499	sie: output_level is disconnected
[admin1@archlinux ~]$ easyeffects 
easyeffects: stream_input_effects.cpp:245	Before: 60 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/output
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/rnnoise directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/output
easyeffects: plugin_base.cpp:499	soe: convolver is disconnected
easyeffects: plugin_base.cpp:499	soe: deesser is disconnected
easyeffects: plugin_base.cpp:499	soe: maximizer is disconnected
easyeffects: stream_input_effects.cpp:245	Before: 60 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: main.cpp:154	Disabling global bypass
QWebEngineDesktopMediaRequest is neither a default constructible QObject, nor a default- and copy-constructible Q_GADGET, nor a QObject marked as uncreatable.
You should not use it as a QML type.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:10:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/Main.qml:223:5: QML ShortcutsSheet: Binding loop detected for property "implicitHeight":
qrc:/qt/qml/org/kde/kirigami/templates/OverlaySheet.qml:139:5
easyeffects: plugin_base.cpp:499	soe: convolver is disconnected
easyeffects: plugin_base.cpp:499	soe: deesser is disconnected
easyeffects: plugin_base.cpp:499	soe: maximizer is disconnected
easyeffects: plugin_base.cpp:499	soe: spectrum is disconnected
easyeffects: plugin_base.cpp:499	soe: output_level is disconnected
easyeffects: plugin_base.cpp:499	sie: spectrum is disconnected
easyeffects: plugin_base.cpp:499	sie: output_level is disconnected

**Comment by wwmm** [comment]
@wxq1884482 the new way to get logs is `easyeffects --debug`. 

In any case I was able to reproduce it @Digitalone1 .  Make sure there is no autoloading profile active and make EE quit instead of just closing its window. In the next start the impulse is loaded and its chart shown. But not the properties with information like name, rate and number of samples. I probably will have to emit a "changed" event for them in an additional location.

**Comment by wwmm** [comment]
> I probably will have to emit a "changed" event for them in an additional location.

Fixed. It was just a matter of changing the onNewKernel signal and slot a little.

**Comment by lIL1521** [comment]
I've found another new issue.
Create a new preset, then double-click to apply this preset. After deleting the preset, the prompt below still shows the original preset name instead of 'No Preset Loaded'.This issue is resolved after completely exiting the software.
This is my reproduction log:

[admin1@archlinux ~]$ easyeffects --debug
easyeffects: main.cpp:138	LV2 search paths: /usr/lib/lv2
easyeffects: pw_manager.cpp:293	Compiled with PipeWire: 1.4.9
easyeffects: pw_manager.cpp:294	Linked to PipeWire: 1.4.9
easyeffects: pw_manager.cpp:172	Core version: 1.4.9
easyeffects: pw_manager.cpp:173	Core name: pipewire-0
easyeffects: pw_metadata_manager.cpp:48	Found metadata: settings
easyeffects: pw_metadata_manager.cpp:48	Found metadata: schema-sm-settings
easyeffects: pw_metadata_manager.cpp:48	Found metadata: persistent-sm-settings
easyeffects: pw_metadata_manager.cpp:48	Found metadata: sm-settings
easyeffects: pw_metadata_manager.cpp:48	Found metadata: sm-objects
easyeffects: pw_metadata_manager.cpp:48	Found metadata: default
easyeffects: pw_metadata_manager.cpp:62	Successfully registered default metadata
easyeffects: pw_metadata_manager.cpp:48	Found metadata: filters
easyeffects: pw_metadata_manager.cpp:48	Found metadata: route-settings
easyeffects: pw_node_manager.cpp:235	Audio/Sink 60 alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI3__sink with serial 290 has been added
easyeffects: pw_node_manager.cpp:235	Audio/Sink 77 alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI2__sink with serial 291 has been added
easyeffects: pw_node_manager.cpp:235	Audio/Sink 110 alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI1__sink with serial 292 has been added
easyeffects: pw_node_manager.cpp:235	Audio/Sink 76 alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink with serial 293 has been added
easyeffects: pw_node_manager.cpp:235	Audio/Source 111 alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic2__source with serial 294 has been added
easyeffects: pw_node_manager.cpp:235	Audio/Source 59 alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source with serial 295 has been added
easyeffects: pw_node_manager.cpp:235	EE/Audio/Sink 90 easyeffects_sink with serial 610 has been added
easyeffects: pw_node_manager.cpp:235	EE/Audio/Source 157 easyeffects_source with serial 611 has been added
easyeffects: pw_metadata_manager.cpp:87	New metadata property: 0, default.configured.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink"}
easyeffects: pw_metadata_manager.cpp:87	New metadata property: 0, default.configured.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source"}
easyeffects: pw_metadata_manager.cpp:87	New metadata property: 0, default.audio.sink, Spa:String:JSON, {"name":"alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink"}
easyeffects: pw_metadata_manager.cpp:101	New default output device: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink
easyeffects: pw_metadata_manager.cpp:87	New metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source"}
easyeffects: pw_metadata_manager.cpp:113	New default input device: alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: pw_metadata_manager.cpp:87	New metadata property: 0, default.video.source, Spa:String:JSON, {"name":"v4l2_input.pci-0000_00_14.0-usb-0_6_1.0"}
easyeffects: pw_device_manager.cpp:199	new Raptor Lake High Definition Audio Controller input route: Stereo Microphone
easyeffects: pw_device_manager.cpp:199	new Raptor Lake High Definition Audio Controller input route: Digital Microphone
easyeffects: pw_device_manager.cpp:210	new Raptor Lake High Definition Audio Controller output route: Headphones
easyeffects: pw_manager.cpp:362	easyeffects_sink node successfully retrieved with id 90 and serial 610
easyeffects: pw_manager.cpp:367	easyeffects_source node successfully retrieved with id 157 and serial 611
easyeffects: lv2_wrapper.cpp:126	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
easyeffects: plugin_base.cpp:464	sie: output_level successfully connected to PipeWire graph
easyeffects: plugin_base.cpp:464	sie: spectrum successfully connected to PipeWire graph
easyeffects: stream_input_effects.cpp:223	Before: 59 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: pw_link_manager.cpp:135	alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source port 44 is connected to  port 144
easyeffects: pw_link_manager.cpp:135	alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source port 42 is connected to  port 141
easyeffects: pw_link_manager.cpp:135	 port 96 is connected to  port 138
easyeffects: pw_link_manager.cpp:135	 port 105 is connected to  port 146
easyeffects: pw_link_manager.cpp:135	 port 147 is connected to easyeffects_source port 94
easyeffects: pw_link_manager.cpp:135	 port 100 is connected to easyeffects_source port 86
easyeffects: lv2_wrapper.cpp:126	http://lsp-plug.in/plugins/lv2/comp_delay_x2_stereo requires feature: http://lv2plug.in/ns/ext/urid#map
easyeffects: plugin_base.cpp:464	soe: output_level successfully connected to PipeWire graph
easyeffects: plugin_base.cpp:464	soe: spectrum successfully connected to PipeWire graph
easyeffects: convolver_kernel_manager.cpp:102	Loaded kernel 'DolbyMusic': 48000 Hz, 1949 samples, 0.041s
easyeffects: convolver.cpp:405	soe: DolbyMusic: kernel correctly loaded
easyeffects: convolver_kernel_fft.cpp:47	Calculating the impulse fft...
easyeffects: convolver_kernel_fft.cpp:73	Min fft frequency: 24.615385055541992
easyeffects: convolver_kernel_fft.cpp:74	Max fft frequency: 23975.384765625
easyeffects: lv2_wrapper.cpp:126	urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/urid#map
easyeffects: lv2_wrapper.cpp:126	urn:zamaudio:ZaMaximX2 requires feature: http://lv2plug.in/ns/ext/options#options
easyeffects: pw_link_manager.cpp:135	 port 129 is connected to alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink port 65
easyeffects: pw_link_manager.cpp:135	 port 132 is connected to alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink port 64
easyeffects: pw_link_manager.cpp:135	 port 139 is connected to  port 106
easyeffects: pw_link_manager.cpp:135	 port 128 is connected to  port 113
easyeffects: plugin_base.cpp:464	soe: maximizer successfully connected to PipeWire graph
easyeffects: pw_link_manager.cpp:135	ee_soe_maximizer port 142 is connected to  port 114
easyeffects: pw_link_manager.cpp:135	ee_soe_maximizer port 58 is connected to  port 143
easyeffects: plugin_base.cpp:464	soe: deesser successfully connected to PipeWire graph
easyeffects: pw_link_manager.cpp:135	ee_soe_deesser port 152 is connected to ee_soe_maximizer port 145
easyeffects: pw_link_manager.cpp:135	ee_soe_deesser port 159 is connected to ee_soe_maximizer port 120
easyeffects: plugin_base.cpp:464	soe: convolver successfully connected to PipeWire graph
easyeffects: pw_link_manager.cpp:135	ee_soe_convolver port 136 is connected to ee_soe_deesser port 72
easyeffects: pw_link_manager.cpp:135	ee_soe_convolver port 70 is connected to ee_soe_deesser port 162
easyeffects: pw_link_manager.cpp:135	easyeffects_sink port 93 is connected to ee_soe_convolver port 43
easyeffects: pw_link_manager.cpp:135	easyeffects_sink port 89 is connected to ee_soe_convolver port 118
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/output
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/rnnoise directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/rnnoise
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/input directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/input
easyeffects: presets_directory_manager.cpp:140	Old /home/admin1/.config/easyeffects/autoload/output directory detected. Migrating its files to /home/admin1/.local/share/easyeffects/autoload/output
easyeffects: presets_directory_manager.cpp:149	Could not copy any file. Aborting migration of /home/admin1/.config/easyeffects/autoload/output
easyeffects: local_server.cpp:56	Local socket server started. Listening on the name: EasyEffectsServer
easyeffects: stream_output_effects.cpp:375	Disconnecting the convolver filter from PipeWire
easyeffects: pw_node_manager.cpp:636	 164 ee_soe_convolver has been removed
easyeffects: plugin_base.cpp:499	soe: convolver is disconnected
easyeffects: stream_output_effects.cpp:375	Disconnecting the deesser filter from PipeWire
easyeffects: pw_node_manager.cpp:636	 140 ee_soe_deesser has been removed
easyeffects: plugin_base.cpp:499	soe: deesser is disconnected
easyeffects: stream_output_effects.cpp:375	Disconnecting the maximizer filter from PipeWire
easyeffects: pw_node_manager.cpp:636	 122 ee_soe_maximizer has been removed
easyeffects: plugin_base.cpp:499	soe: maximizer is disconnected
easyeffects: pw_link_manager.cpp:135	 port 129 is connected to alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink port 65
easyeffects: pw_link_manager.cpp:135	 port 132 is connected to alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink port 64
easyeffects: pw_link_manager.cpp:135	 port 139 is connected to  port 106
easyeffects: pw_link_manager.cpp:135	 port 128 is connected to  port 113
easyeffects: plugin_base.cpp:464	soe: maximizer successfully connected to PipeWire graph
easyeffects: pw_link_manager.cpp:135	ee_soe_maximizer port 142 is connected to  port 114
easyeffects: pw_link_manager.cpp:135	ee_soe_maximizer port 160 is connected to  port 143
easyeffects: plugin_base.cpp:464	soe: deesser successfully connected to PipeWire graph
easyeffects: pw_link_manager.cpp:135	ee_soe_deesser port 152 is connected to ee_soe_maximizer port 58
easyeffects: pw_link_manager.cpp:135	ee_soe_deesser port 163 is connected to ee_soe_maximizer port 71
easyeffects: plugin_base.cpp:464	soe: convolver successfully connected to PipeWire graph
easyeffects: pw_link_manager.cpp:135	ee_soe_convolver port 136 is connected to ee_soe_deesser port 159
easyeffects: pw_link_manager.cpp:135	ee_soe_convolver port 148 is connected to ee_soe_deesser port 134
easyeffects: pw_link_manager.cpp:135	easyeffects_sink port 93 is connected to ee_soe_convolver port 70
easyeffects: pw_link_manager.cpp:135	easyeffects_sink port 89 is connected to ee_soe_convolver port 116
easyeffects: stream_input_effects.cpp:223	Before: 59 -> alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source
easyeffects: pw_link_manager.cpp:135	alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source port 44 is connected to  port 144
easyeffects: pw_link_manager.cpp:135	alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Mic1__source port 42 is connected to  port 141
easyeffects: pw_link_manager.cpp:135	 port 96 is connected to  port 138
easyeffects: pw_link_manager.cpp:135	 port 105 is connected to  port 146
easyeffects: pw_link_manager.cpp:135	 port 147 is connected to easyeffects_source port 94
easyeffects: pw_link_manager.cpp:135	 port 100 is connected to easyeffects_source port 86
easyeffects: main.cpp:154	Disabling global bypass
QWebEngineDesktopMediaRequest is neither a default constructible QObject, nor a default- and copy-constructible Q_GADGET, nor a QObject marked as uncreatable.
You should not use it as a QML type.
qrc:/qt/qml/ee/ui/contents/ui/PageStreamsEffects.qml:10:1: QML PageStreamsEffects: Created graphical object was not placed in the graphics scene.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qt.graphs2d.series: points list size is 0, can't calculate spline points.
qrc:/qt/qml/ee/ui/contents/ui/Main.qml:223:5: QML ShortcutsSheet: Binding loop detected for property "implicitHeight":
qrc:/qt/qml/org/kde/kirigami/templates/OverlaySheet.qml:139:5
easyeffects: global_shortcuts.cpp:90	D-Bus session for GlobalShortcuts created.
easyeffects: presets_manager.cpp:352	Saved preset: /home/admin1/.local/share/easyeffects/output/123.json
easyeffects: presets_manager.cpp:524	Successfully loaded the preset: /home/admin1/.local/share/easyeffects/output/123.json
easyeffects: stream_input_effects.cpp:182	No app linked to our device wants to play. Unlinking our filters.
easyeffects: stream_output_effects.cpp:184	No app linked to our device wants to play. Unlinking our filters.
easyeffects: stream_output_effects.cpp:375	Disconnecting the convolver filter from PipeWire
easyeffects: pw_node_manager.cpp:636	 164 ee_soe_convolver has been removed
easyeffects: plugin_base.cpp:499	soe: convolver is disconnected
easyeffects: stream_output_effects.cpp:375	Disconnecting the deesser filter from PipeWire
easyeffects: pw_node_manager.cpp:636	 140 ee_soe_deesser has been removed
easyeffects: plugin_base.cpp:499	soe: deesser is disconnected
easyeffects: stream_output_effects.cpp:375	Disconnecting the maximizer filter from PipeWire
easyeffects: pw_node_manager.cpp:636	 122 ee_soe_maximizer has been removed
easyeffects: plugin_base.cpp:499	soe: maximizer is disconnected
easyeffects: presets_manager.cpp:382	Removed preset: /home/admin1/.local/share/easyeffects/output/123.json
qrc:/qt/qml/org/kde/desktop/ScrollBar.qml:78:13: TypeError: Cannot read property 'horizontal' of null

Looking forward to your reply.

> [@wxq1884482](https://github.com/wxq1884482) the new way to get logs is `easyeffects --debug`.
> 
> In any case I was able to reproduce it [@Digitalone1](https://github.com/Digitalone1) . Make sure there is no autoloading profile active and make EE quit instead of just closing its window. In the next start the impulse is loaded and its chart shown. But not the properties with information like name, rate and number of samples. I probably will have to emit a "changed" event for them in an additional location.

**Comment by Digitalone1** [comment]
The loaded preset is much more an indication of "the last loaded preset". Indeed, if you load a preset and then change the configuration, it's not that preset anymore, but you still loaded it the last time.

**Comment by Digitalone1** [comment]
> This issue is resolved after completely exiting the software. 

You can also load another preset to refresh it. Anyway, if I remember correctly, we were writing `Last Loaded Preset` in the GTK version.

**Comment by lIL1521** [comment]
> The loaded preset is much more an indication of "the last loaded preset". Indeed, if you load a preset and then change the configuration, it's not that preset anymore, but you still loaded it the last time.

But in reality, it doesn't seem to have loaded; the interface just shows it as loaded, and the console gives an error log.

easyeffects: presets_manager.cpp:382 Removed preset: /home/admin1/.local/share/easyeffects/output/123.json
qrc:/qt/qml/org/kde/desktop/ScrollBar.qml:78:13: TypeError: Cannot read property 'horizontal' of null

**Comment by lIL1521** [comment]
> > This issue is resolved after completely exiting the software.
> 
> You can also load another preset to refresh it. Anyway, if I remember correctly, we were writing `Last Loaded Preset` in the GTK version.

You can indeed do this, or completely close the software to restore the original prompt situation. The problem lies with the prompt.

**Comment by Digitalone1** [comment]
> qrc:/qt/qml/org/kde/desktop/ScrollBar.qml:78:13: TypeError: Cannot read property 'horizontal' of null

This is not our error. 

> You can indeed do this

Maybe. @wwmm what do you think? I can change it.

**Comment by wwmm** [comment]
>what do you think? I can change it.

I think we should just clear the last loaded preset property and the presets window status after the preset that was marked as last used is removed. This will probably benefit #4541 too.
